# Generated by Django 4.2 on 2023-04-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota01', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota02', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota03', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota04', models.DecimalField(decimal_places=2, max_digits=5)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
    ]
