# Generated by Django 4.2 on 2023-04-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_nota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'curso')},
        ),
    ]
