# Generated by Django 4.2 on 2023-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='tipo_documento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'otro')], max_length=1),
        ),
    ]
