# Generated by Django 4.2 on 2023-04-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0003_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=1)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.periodo')),
                ('postCHOISE_INGRESOulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.postulante')),
            ],
        ),
    ]
