# Generated by Django 4.2 on 2023-04-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0006_alter_matricula_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('periodo',)},
        ),
    ]
